baseURL: "https://ZeroTrustZeroTouch.com"
languageCode: "en-us"
title: "Zero Trust Zero Touch"
theme: Public-Profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 4
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: Offerings
      name: Offerings
      title: Offerings
      url: /offerings
      weight: 1
    - identifier: About Zero Trust Zero Touch
      name: About Zero Trust Zero Touch
      title: About Zero Trust Zero Touch
      url: /about/us/
      weight: 2
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Zero Trust Zero Touch"
  description: Zero Trust Zero Touch IT Management Solutions
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon-white.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
     disableThemeToggle: true
     defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    #brandLogo: "/images/logo-white.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "Zero Trust Zero Touch" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: false
    intro: ""
    title: ""
    subtitle: ""
    content: 
    #image: /images/headshot-2.png
    bottomImage:
      enable: false
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: ""
      url: ""
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        #- icon: fab fa-github
        #  url: https://example.com
        - icon: fa-brands fa-linkedin
          url: 
      #customIcons:
      #  - icon: /fav.png
      #    url: ""

  # About
  about:
    enable: true
    title: "About Us"
    #image: ""
    content: |-
      Our professional philosophy is encapsulated in the motto: "Human-Centric" and "Make future me less unhappy". In practical terms, this translates to implementing solutions today that won't become tomorrow's technical debt, and removing barriers. This forward-thinking approach ensures that the IT infrastructure put in place remains robust, scalable, and adaptable to future technological advancements. It's a proactive strategy that saves time, resources, and potential headaches down the line.
      One of the cornerstones of our approach is the creation and maintenance of functional, living documentation. We're strong advocates for utilizing dedicated IT documentation tools such as ITGlue, Hudu, or more recently, ITFlow. These platforms serve as centralized repositories for all IT-related information, making it easily accessible and updatable. This commitment to comprehensive documentation is not just about record-keeping; it's about creating a knowledge base that evolves with the organization's IT landscape.
      
    skills:
      enable: true
      title: "Here are a few of the problems we work to solve:"
      items:
        - "Patching, Inventory and Endpoint Compliance"
        - "Network Connectivity: Wired, Wireless, Remote, and Zero Trust"
        - "Infrastructure Management: Inventory, Lifecycle, Integrations, and Availability"
        - "Security: Policies, Procedures, Best Practices and How staff actually operate"
        - "Documentation, Auditing and Reporting"
        - "Backups: Endpoint, Infrastructure and Cloud"
        - "Cloud Platform Management"
        - "Vendor Relationships"
        - "IT Security: Endpoint, Infrastructure, Networking and Cloud"
        - "IT Operations: What needs to happen, Who needs to do it, and Who to call when there are issues"
        - "Process Mapping and Improvements: How long does this take, Who needs to be involved, How can we reduce errors"
        - "Modernization and Migrations: Why do we it this way, Are there better ways, How do we get there"

 # Offerings
  projects:
    enable: true
    title: "Our Offerings"
    items:
      - title: Managed Services
        content: We offer a two broad ranges of Managed services, Simple IT Management for SMBs, and Co-Managed Solutions for SMEs. Both have Flexible offerings with a Tiers of services that work for you business needs.  The Small Business Offerings are designed to offload the Risk and minutia  of IT Management from SMBs, while the Co-Managed solution is designed to be highly flexible to suit your organization's needs, be they de-escalation, delegation, Security, Compliance or any of the myriad od needs that modern enterprises require.
        featured:
          name: Managed Managed
          link: /offerings/managed-services
      - title: Fractional Services
        content: A line of offerings for those with a need to access to high level resources on their team, but don't have the workload or budget for a full FTE.  Fractional offerings typically fit with clients who need a broad range of skills such as Networking and Infrastructure, or Project Delivery. The offerings listed are a starting point of what our agent pool offers, the listed services represent common needs that we have been tasked to solve, and are by no mean exhaustive.
        featured:
          name: Fractional Services
          link: /offerings/fractional-services
      - title: CyberSecurity Services
        content: Our line CyberSecurity Services available Ad-Hoc or utilized as adjuncts to our Fractional and Managed offerings. They are comprised of several discrete offerings to be paired with other offerings to form complete solutions that fit your unique business needs.
        featured:
          name: Cyber Services
          link: /offerings/cyber-services
      - title: Professional Services
        content: Professional Services available Ad-Hoc or utilized as adjuncts to our Fractional and Managed offerings.
        featured:
          name: Professional Services
          link: /offerings/professional-services

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: If you have any questions feel free to reach out via email
    btnName: Contact us
    btnLink: mailto:contact@zerotrustzerotouch.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "/Offerings"
      count: 4
      title: My Offerings
      enable: true
      disableFeaturedImage: true
    socialNetworks:
      #github: https://github.com
      linkedin: https://ca.linkedin.com/company/zerotrustzerotouch
      

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>